name: CI

on: [push]

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Restore Cache
      uses: actions/cache@preview
      id: cache
      with:
        path: ~/go/pkg
        key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

    - name: Get dependencies
      run: |
        go mod download

    - name: Test
      run: |
        go test ./...

    - name: Build
      run: |
        go build -o paralleltasks github.com/matdurand/paralleltasks/cmd
